{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "myaks.serviceAccountName" . }}
  labels:
{{ include "myaks.labels" . | nindent 4 }}
{{- end -}}
